# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: ukroma
  password: password

development:
  <<: *default
  database: qna_development


test:
  <<: *default
  database: qna_test


production:
  <<: *default
  database: qna_production
  username: qna
  password: <%= ENV['QNA_DATABASE_PASSWORD'] %>
